### ISSUE TITLE
Release v1.0.0 Stable

### ISSUE THREAD

**Issue by nitky** [nttcom/metemcyber#103]
I'd like to have a solid plan for getting v1.

# TODO
- [ ] metemctl new
- [ ] metemctl ix
  - [ ] info
  - [ ] latest 
  - [ ] search [title]
  - [ ] get [index]
  - [ ] use [token address] [optional: operator address]
- [ ] metemctl run
- [ ] metemctl check [workflow uuid]]
- [ ] metemctl publish [workflow uuid]
- [ ] metemctl contract
  - [ ] delete [contract_address]
  - [ ] code  [contract_address]
  - [ ] token
    - [ ] new
    - [ ] mint [token_address]
    - [ ] burn [token_address]
    - [ ] info [token_address]
  - [ ] operator
    - [ ] new
    - [ ] info
    - [ ] get (=info)
    - [ ] set
  - [ ] broker
    - [ ] new
    - [ ] info
    - [ ] get  (=info)
    - [ ] set
  - [ ] catalog
    - [ ] info
    - [ ] list  (=info)
    - [ ] new
    - [ ] add
    - [ ] remove
    - [ ] ractivate
    - [ ] rdeactive
    - [ ] rdefault
  - [ ] metemctl account
    - [ ] new
    - [ ] add
    - [ ] emove
    - [ ] info
    - [ ] default
  - [ ] metemctl misp
    - [ ] info
    - [ ] open
    - [ ] fetch
    - [ ] post
  - [ ] metemctl console
  - [ ] metemctl config
    - [ ] info
    - [ ] get [section.option]
    - [ ] set [section.option]
  - [ ] metemctl external-links
  - [ ] metemctl seeker
  - [ ] metemctl solver
